name: canswerist
favicon: null
layout_spectrum: 0.9245225104968995
typography_spectrum: 0.75198
title: Canswerist.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050506'
    - '#5a455c'
    - '#9a7083'
    - '#e5a2c9'
    - '#f6e2ef'
  brandStrength: 0.7403788364026695
  lightness: 0.9646708115469664
  saturation: 0.5
  rhythmicContrast: 0.032126693753525615
purpose: []
